spring:
  redis:
    host: 192.168.10.204
    port: 6379
  application:
    name: api-gateway
  cloud:
    config:
      discovery:
        enabled: false
        service-id: CONFIG
  rabbitmq:
      host: 192.168.10.204
      username: guest
      password: guest
      port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8083
