spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://127.0.0.1:3306/order?characterEncoding=utf8&useSSL=false
  jpa:
      show-sql: true
  application:
    name: order
  cloud:
    config:
      discovery:
        enabled: false
        service-id: CONFIG
      profile: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
env: dev1
