spring:
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     username: root
     password: root
     url: jdbc:mysql://127.0.0.1:3306/order_product?characterEncoding=utf8&useSSL=false
  jpa:
     show-sql: true
  application:
     name: product
  cloud:
     config:
       discovery:
         enabled: false
         service-id: CONFIG
       profile: dev
  rabbitmq:
     host: 192.168.10.204
     username: guest
     password: guest
     port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080
